name: Compress system.img

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Download system.img
        run: |
          pip install requests
          git clone --depth 1 https://github.com/ltsdw/gofile-downloader.git
          cd gofile-downloader
          python3 gofile-downloader.py "https://gofile.io/d/06fn5ZVb"
          F=$(find . -type f -not -path './.git/*' -not -name '*.py' -not -name '*.md' -printf '%s %p\n' | sort -rn | head -n1 | cut -d' ' -f2-)
          mv "$F" "$GITHUB_WORKSPACE/system.img"
          cd "$GITHUB_WORKSPACE"
          ls -lh system.img

      - name: Compress
        run: |
          xz -9e -T0 -k -v system.img
          ls -lh system.img.xz

      - name: Upload to Gofile
        run: |
          RESP=$(curl -s -F "file=@system.img.xz" https://upload.gofile.io/uploadfile)
          echo "$RESP"
          LINK=$(echo "$RESP" | jq -r .data.downloadPage)
          echo "Gofile link: $LINK"
          echo "### Gofile link: $LINK" >> $GITHUB_STEP_SUMMARY
